server:
  port: 9000
spring:
  application:
    name: downing-common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/down?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&useTimezone=true&serverTimezone=GMT%2b8
    username: root
    password:
    hikari:
      auto-commit: false
  jpa:
    showSql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true