server:
  port: 9003
spring:
  application:
    name: downing-mq
  rabbitmq:
    host: localhost
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka