server:
  port: 9999
spring:
  application:
    name: downing-eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:${server.port}/eureka/